### PR TITLE
👷‍♂️ Add `awesome_bot` to CI pipeline

### PR DESCRIPTION
**Pull request by pcaversaccio**
As title. I also quickly prettified the `README` & added a CI badge to the `README`. Let's see whether the CI completes successfully [here](https://github.com/pcaversaccio/On-Chain-Investigations-Tools-List/actions/runs/4182546036/jobs/7245765411).

### CODE REVIEW

**Comment by pcaversaccio** [comment]
no need for the CI?

**Comment by pcaversaccio** [comment]
Rerunning the CI test after your fixes [here](https://github.com/pcaversaccio/On-Chain-Investigations-Tools-List/actions/runs/4182905238/jobs/7246588314).

**Comment by pcaversaccio** [comment]
There are still some issues, fyi 

image

**Comment by OffcierCia** [comment]
Thank you so much!

**Comment by OffcierCia** [comment]
Thank you so much for your help! I prefer hardcore and will make all changes manually based on this information! 🙂

**Comment by pcaversaccio** [comment]
sure :-D

**Pull request closed without merging**
